"""add user portfolio and config models

Revision ID: 4bee119393f6
Revises: c6ad6ca0d21c
Create Date: 2025-03-31 14:44:31.371470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bee119393f6'
down_revision = 'c6ad6ca0d21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration_value', schema=None) as batch_op:
        batch_op.drop_constraint('unique_category_value', type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.alter_column('is_asset',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('investment_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('investment_mode',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('is_asset',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('configuration_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.create_unique_constraint('unique_category_value', ['category', 'value'])

    # ### end Alembic commands ###
